version: '3.8'

services:
  dropsafe-main:
    build: .
    ports:
      - "8499:8499"
    volumes:
      - ./shared_data:/app/shared_data
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8499
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    networks:
      - dropsafe-network

  dropsafe-teacher:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./shared_data:/app/shared_data
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    networks:
      - dropsafe-network

  dropsafe-student:
    build: .
    ports:
      - "8502:8502"
    volumes:
      - ./shared_data:/app/shared_data
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    networks:
      - dropsafe-network

  dropsafe-counsellor:
    build: .
    ports:
      - "8504:8504"
    volumes:
      - ./shared_data:/app/shared_data
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8504
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped
    networks:
      - dropsafe-network

networks:
  dropsafe-network:
    driver: bridge